### ISSUE TITLE
To package or not to package

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/MINLPLib.jl#10]
Based on your PR on https://github.com/lanl-ansi/minlp-solvers I am wondering is your intention for this repo to be a Julia package or just a bunch of standalone data and scripts?

**Comment by sanfranciscocarrot** [comment]
Julia package, I think. Although the package can be large, the problem loading scheme is designed to be light-weighted. I also hope to provide some simpler interface to provide users with problem info. What do you think?

**Comment by ccoffrin** [comment]
Ok given that, the naming convention for a Julia packages is camel case ending with `.jl`.

**Comment by harshangrjn** [comment]
Closing this for now, as this has ended up being a package. If need be, we can open this back.
