### ISSUE TITLE
Turning this repo into a host for minlp instances of format .jl

### ISSUE THREAD

**Issue by sanfranciscocarrot** [lanl-ansi/MINLPLib.jl#2]

**Comment by ccoffrin** [comment]
how about calling this `minlplib2-jump`?  I think that's more descriptive.

**Comment by sanfranciscocarrot** [comment]
minlplib2 may be too general since there are other libraries available, e.g., GLOBALLib, LINLib, MacMOOPLib, PrincetonLib. How about just `minlp-jump`?

**Comment by ccoffrin** [comment]
Oh if that is the case then `minlplib-jump` would seem reasonable, with subdirectories for which archives the test cases come from.
