### ISSUE TITLE
reducing the size of the repo

### ISSUE THREAD

**Issue by sanfranciscocarrot** [lanl-ansi/MINLPLib.jl#23]
Potentially, compressing each instance can be a feasible idea. When a user asks for a model, extract the file and create a temp version, after the model is loaded, the temp version is deleted. 
A quick test: if each .jl instances is compressed with .tar.gz, then we are looking at approximately 1/10 of the current size.

**Comment by sanfranciscocarrot** [comment]
Compress the repo for fast download and use build to expand locally

**Comment by ccoffrin** [comment]
git does compression automatically on transfer so you should check if this will provide a performance improvement.

**Comment by sanfranciscocarrot** [comment]
The reduced package roughly reduced 10s (4.5M/s download, git clone 2min06sec -> 1min54sec), which is not a major breakthrough. The size of the entire package is 1.9G.

toJuMP.jl currently support writing variables attributes (bounds, warm-start, category) in loops, which can be a significant reduction in file size. I should give that a measurement.
