### ISSUE TITLE
Further stripping gms2jump functions

### ISSUE THREAD

**Issue by sanfranciscocarrot** [lanl-ansi/MINLPLib.jl#4]
@ccoffrin I want to strip those functionalities to as another repo (toJuMP.jl) under my Github. What do you think?

**Comment by ccoffrin** [comment]
Either way is fine, mostly a matter of preference.  Think about what will be easiest for future maintenance.

if the gms2jump is sufficiently robust you might consider making it a Julia package.  I am sure other JuMP users would like this.
