### ISSUE TITLE
Example in Readme is broken for Julia 1.6

### ISSUE THREAD

**Issue by mewilhel** [lanl-ansi/MINLPLib.jl#41]
The sample code presented at the bottom of the readme is broken for Julia 1.6

```julia
for lib in ["bcp", "global", "ibm", "inf", "minlp", "minlp2"]
    NAMES = MINLPLib.fetch_names(lib)   # Fetch a list of instance names
    for i in NAMES
        Meta = MINLPLib.fetch_meta(lib, i)  # Fetch instance meta
        isempty(Meta) && continue
        !haskey(Meta, "NLOPERATOR") && continue
        if "exp" in M["NLOPERATOR"][1]
            MINLPLib.add_to_lib("USERLib", lib, i)  # Collect instance
        else
            continue
        end
    end
end
println(MINLPLib.fetch_names("USERLib"))
```

basically no `M` is defined and the `in` statement should be replaced with `occursin`, so the corrected version would be

```julia
for lib in ["bcp", "global", "ibm", "inf", "minlp", "minlp2"]
    NAMES = MINLPLib.fetch_names(lib)   # Fetch a list of instance names
    for i in NAMES
        Meta = MINLPLib.fetch_meta(lib, i)  # Fetch instance meta
        isempty(Meta) && continue
        !haskey(Meta, "NLOPERATOR") && continue
        if occursin("exp", Meta["NLOPERATOR"][1])
            MINLPLib.add_to_lib("USERLib", lib, i)  # Collect instance
        else
            continue
        end
    end
end
println(MINLPLib.fetch_names("USERLib"))
```

when these changes are made there is an `UndefVarError: warn not defined` thrown. I think that the usage of `warn()` was phased out in Julia 1.0 in favor of `@warn`. Mind if I throw in a pull request to resolve these issues?

**Comment by harshangrjn** [comment]
@mewilhel Thanks! Please feel free to send a PR which fixes these issues.

**Comment by harshangrjn** [comment]
@mewilhel Before sending the PR, please update your repo as numerous changes were just merged into the master, in order to support JuMP v0.21+.

**Comment by mewilhel** [comment]
Thanks for the heads up! It should be even the with master (except the change to the readme).
